### ISSUE TITLE
Representing HSK level visually

### ISSUE THREAD

**Issue by IdiosApps** [danielt998/HanziToAnki#11]
A mostly transparent highlight could be placed around characters, to let the user know their HSK level. Could be a nice customisable feature.

**Comment by james-clark-5** [comment]
I think this could get quite messy, especially when combined with representing tones by colouring text. 

I think the user would probably only want to see which HSK level a word is when they see the answer of an Anki card. Because Anki styles the Front and the Back with the same Styling, HanziToAnki may have to output hsk-formatted (and colour-formatted, and colour-&-hsk-formatted?) character/pinyin fields.

**Comment by james-clark-5** [comment]
Also, whilst this could be useful, it may subtly make users think "the hsk level for this character is too high for me now, I'll ignore it" - even if its a word that could be particularly useful to them.
